### ISSUE TITLE
Anticipated runtime -- running for 1 week so far

### ISSUE THREAD

**Issue by mebbert** [institut-de-genomique/NaS#7]
Hi,

We're working on a ~2.5 gigabase genome with ~30x illumina coverage, but only 3,338 Nanopore reads (N50=4699). NaS has been running for a full week (on sensitive mode) and is still retrieving similar reads.

We gave NaS 8 threads on a pretty high-end machine. Do you have an estimate for how long it should take?

Thanks!

**Comment by bistace** [comment]
Hi,
30X of Illumina reads for a 2.5Gb genome represents 75Gb. Although you have few Nanopore reads, the quantity of short reads is quite high. We don't recommend using NaS on genomes larger than 20Mb due to the runtime which may be of several weeks. We never tested it on such a large genome but the running time could be close to a month.

**Comment by mebbert** [comment]
Thank you.
